name: Install wasm-pack & binaryen tools
description: 'Installs wasm-pack and binaryen tools for WebAssembly development with caching support.'
author: RoMarketplace Team (romarketplace-com)
branding:
  icon: 'download-cloud'
  color: 'blue'
inputs:
  wasm-pack-version:
    description: 'Version of wasm-pack to install'
    required: false
    default: 'latest'
  binaryen-version:
    description: 'Version of binaryen to install'
    required: false
    default: 'latest'
runs:
  using: 'node20'
  main: 'lib/index.js'